import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

const stories: Record<string, any[]> = {
  Shaanxi: [
    { type: 'intro', title: 'The Ancient Capital', narrative: "Lily arrives in Xi'an by high-speed train. The city walls loom ahead — the most complete ancient city walls in China. She checks her grandma's journal: 'Xi'an — where 13 dynasties began. Walk the walls and feel history under your feet.'", speaker: 'narrator', mood: 'excited', dialogue: "Lily: 'Grandma walked these same walls 40 years ago. I'm literally following in her footsteps.'" },
    { type: 'learn', title: 'Time Words', narrative: "Lily checks her watch. The Terracotta Warriors museum opens at 9am. She needs to ask about times and dates.", speaker: 'lily', mood: 'focused', dialogue: "Lily: 'I need to know: what time does it open? When should I go?'", words: [{ character: '今天', pinyin: 'jīn tiān', english: 'Today', context: 'Today Lily visits the warriors.' }, { character: '明天', pinyin: 'míng tiān', english: 'Tomorrow', context: 'Tomorrow she explores the Muslim Quarter.' }, { character: '点', pinyin: 'diǎn', english: "O'clock", context: 'The museum opens at 9 o\'clock.' }, { character: '几', pinyin: 'jǐ', english: 'How many (≤10)', context: 'What time? 几点?' }] },
    { type: 'quiz', title: 'Museum Hours', narrative: 'Lily asks a guard at the museum entrance.', dialogue: "Lily: 请问，几点开门？(Excuse me, what time does it open?)", question: 'What is Lily asking?', options: ['Where is the museum?', 'What time does it open?', 'How much is the ticket?', 'Can I take photos?'], answer: 'What time does it open?', feedback: "The guard smiles. '九点!' (9 o'clock!) Lily checks her watch — 8:45. Perfect timing!" },
    { type: 'learn', title: 'Asking Questions', narrative: "Inside the museum, Lily is overwhelmed by thousands of warriors. She has so many questions.", speaker: 'lily', mood: 'curious', dialogue: "Lily: 'Who made these? How many are there? I need question words!'", words: [{ character: '什么', pinyin: 'shén me', english: 'What', context: 'What is this? 这是什么？' }, { character: '谁', pinyin: 'shuí', english: 'Who', context: 'Who made these? 谁做的？' }, { character: '多少', pinyin: 'duō shao', english: 'How many/much', context: 'How many warriors? 多少兵马俑？' }] },
    { type: 'quiz', title: 'A Curious Traveler', narrative: 'Lily wants to ask the guide how many warriors were buried.', dialogue: "Guide: 这里有八千多个兵马俑。(There are over 8,000 warriors here.)", question: 'What question did Lily probably ask?', options: ['谁做的？(Who made them?)', '多少钱？(How much?)', '多少个？(How many?)', '几点？(What time?)'], answer: '多少个？(How many?)', feedback: "'八千多个!' the guide says. Lily's jaw drops. Eight THOUSAND life-sized warriors, each with a unique face." },
    { type: 'end', title: 'Following Footsteps', narrative: "That evening, Lily walks the city walls at sunset. The ancient stones glow orange. She writes in her journal:", speaker: 'lily', mood: 'reflective', dialogue: "Day 3. I walked where emperors walked. I learned to ask questions — 什么, 谁, 多少. A guide told me each warrior has a different face. Like each person I meet here. Grandma, I'm starting to hear your voice in this language." },
  ],
  Sichuan: [
    { type: 'intro', title: 'Too Spicy!', narrative: "Lily arrives in Chengdu to the smell of chili oil and Sichuan peppercorns. Her hostel owner immediately offers her hotpot. 'It's the local specialty!' Lily is excited — and terrified.", speaker: 'narrator', mood: 'nervous', dialogue: "Lily: 'I've heard Sichuan food is spicy. But how spicy can it really be?'" },
    { type: 'learn', title: 'Food & Eating', narrative: "At the hotpot restaurant, the bubbling red broth looks like lava. Lily needs to order food.", speaker: 'lily', mood: 'nervous', dialogue: "Waiter: 你想吃什么？(What do you want to eat?)\nLily: 'I need food words. Fast.'", words: [{ character: '吃', pinyin: 'chī', english: 'To eat', context: 'I want to eat hotpot. 我想吃火锅。' }, { character: '喝', pinyin: 'hē', english: 'To drink', context: 'I want to drink tea. 我想喝茶。' }, { character: '水', pinyin: 'shuǐ', english: 'Water', context: 'Lily needs water after spicy food!' }, { character: '米饭', pinyin: 'mǐ fàn', english: 'Rice', context: 'Rice helps with the spice.' }] },
    { type: 'quiz', title: 'First Bite', narrative: "Lily takes her first bite. Her mouth is ON FIRE.", dialogue: "Lily: (eyes watering) '太...太...' (Too... too...)", question: 'What word should Lily use?', options: ['太辣了！(Too spicy!)', '太冷了！(Too cold!)', '太好了！(Great!)', '太少了！(Too little!)'], answer: '太辣了！(Too spicy!)', feedback: "The waiter laughs kindly and hands her a glass of milk. 'Sichuan people eat this every day!' Lily can't imagine." },
    { type: 'learn', title: 'Panda Love', narrative: "The next day, Lily volunteers at the Chengdu Panda Base. She's surrounded by baby pandas.", speaker: 'lily', mood: 'happy', dialogue: "Lily: 'These pandas are... there's no word. Wait, yes there is!'", words: [{ character: '可爱', pinyin: 'kě ài', english: 'Cute', context: 'Pandas are too cute! 熊猫太可爱了！' }, { character: '大', pinyin: 'dà', english: 'Big', context: 'Adult pandas are big.' }, { character: '小', pinyin: 'xiǎo', english: 'Small', context: 'Baby pandas are small.' }, { character: '喜欢', pinyin: 'xǐ huān', english: 'To like', context: 'I like pandas. 我喜欢熊猫。' }] },
    { type: 'quiz', title: 'Tea House Culture', narrative: "After the panda base, Lily visits a traditional tea house. The tea master performs an elegant ceremony.", dialogue: "Tea master: 请喝茶。(Please drink tea.)", question: 'How does Lily say "I like drinking tea"?', options: ['我喜欢喝茶', '我喝茶很大', '茶太辣了', '我喜欢吃茶'], answer: '我喜欢喝茶', feedback: "The tea master nods approvingly. Lily sits back and enjoys her jasmine tea. This is 巴适 (bāshì) — the Chengdu word for 'everything is just right.'" },
    { type: 'end', title: 'Finding 巴适', narrative: "Lily writes in her journal at the tea house.", speaker: 'lily', mood: 'reflective', dialogue: "I ate fire today. I learned '太辣了' the hard way. But I also learned '可爱' — because pandas. And I discovered 巴适 — the feeling when everything is simply, perfectly good. Chengdu, you've taught me well." },
  ],
  Shanghai: [
    { type: 'intro', title: 'City of the Future', narrative: "Lily steps out of Shanghai Hongqiao Station into a canyon of glass skyscrapers. After ancient Xi'an and laid-back Chengdu, Shanghai feels like the future.", speaker: 'narrator', mood: 'excited', dialogue: "Lily: 'Everything here sparkles. I feel like I need to upgrade my entire wardrobe just to fit in.'" },
    { type: 'learn', title: 'Shopping', narrative: "Lily hits Nanjing Road — China's most famous shopping street. She needs shopping vocabulary.", speaker: 'lily', mood: 'excited', dialogue: "Lily: 'I want to buy something. But I don't know how to ask the price!'", words: [{ character: '买', pinyin: 'mǎi', english: 'To buy', context: 'I want to buy this. 我想买这个。' }, { character: '钱', pinyin: 'qián', english: 'Money', context: 'How much money? 多少钱？' }, { character: '多少', pinyin: 'duō shao', english: 'How much', context: 'How much is this? 这个多少钱？' }, { character: '商店', pinyin: 'shāng diàn', english: 'Shop', context: 'Nanjing Road has many shops.' }] },
    { type: 'quiz', title: 'At the Market', narrative: "Lily finds a beautiful silk scarf. She wants to know the price.", dialogue: "Vendor: 很漂亮，对不对？(Beautiful, right?)", question: 'What should Lily ask?', options: ['这个多少钱？', '这是什么？', '你叫什么名字？', '现在几点？'], answer: '这个多少钱？', feedback: "'八十块!' the vendor says. 80 yuan. Lily's first shopping interaction in Chinese — and it worked!" },
    { type: 'learn', title: 'The Bund', narrative: "At sunset, Lily walks the Bund. The colonial buildings on one side, neon skyscrapers on the other.", speaker: 'narrator', mood: 'inspired', dialogue: "Lily: 'This is the most beautiful skyline I've ever seen. I need the word for beautiful.'", words: [{ character: '漂亮', pinyin: 'piào liang', english: 'Beautiful', context: 'The Bund is beautiful. 外滩很漂亮。' }, { character: '大', pinyin: 'dà', english: 'Big', context: 'Shanghai is a big city.' }, { character: '有', pinyin: 'yǒu', english: 'To have', context: 'Shanghai has many buildings.' }] },
    { type: 'quiz', title: 'Soup Dumplings', narrative: "Lily tries xiaolongbao — Shanghai's famous soup dumplings.", dialogue: "Server: 小心！很烫！(Careful! Very hot!)", question: 'Lily wants to say "This is too delicious!" What should she say?', options: ['太好吃了！(Too delicious!)', '太辣了！(Too spicy!)', '太冷了！(Too cold!)', '太大了！(Too big!)'], answer: '太好吃了！(Too delicious!)', feedback: "The soup bursts in her mouth — rich, savory, perfect. Lily understands why people line up for hours." },
    { type: 'end', title: 'East Meets West', narrative: "Lily writes on the Bund at night.", speaker: 'lily', mood: 'reflective', dialogue: "I bought a scarf. I ate soup dumplings. I told a vendor '很漂亮' — and meant it. Shanghai feels like two cities in one: old and new, East and West. Grandma's journal says she came here in 1985, when Pudong was still farmland. Now it touches the clouds." },
  ],
  Yunnan: [
    { type: 'intro', title: 'South of the Clouds', narrative: "Lily flies to Kunming — the 'City of Eternal Spring.' The air is fresh, the sky impossibly blue. Her grandma's journal says: 'Yunnan is where China keeps its secrets.'", speaker: 'narrator', mood: 'peaceful', dialogue: "Lily: 'Kunming has perfect weather. Not hot, not cold. I could stay here forever.'" },
    { type: 'learn', title: 'Weather & Nature', narrative: "Lily hikes the Stone Forest. The limestone pillars rise like petrified trees. She needs nature words.", speaker: 'lily', mood: 'exploring', dialogue: "Lily: 'The weather is perfect for hiking. But I need words to describe it!'", words: [{ character: '天气', pinyin: 'tiān qì', english: 'Weather', context: 'The weather is great. 天气很好。' }, { character: '冷', pinyin: 'lěng', english: 'Cold', context: 'It is not cold in Kunming.' }, { character: '热', pinyin: 'rè', english: 'Hot', context: 'Summer in Yunnan is not too hot.' }, { character: '好', pinyin: 'hǎo', english: 'Good', context: 'The weather is good!' }] },
    { type: 'quiz', title: 'Mountain Directions', narrative: "Lily gets a bit lost on the trail. She needs to ask for directions.", dialogue: "Hiker: 你要去哪里？(Where are you going?)", question: 'How does Lily ask "Where is the exit?"', options: ['出口在哪儿？', '你好吗？', '多少钱？', '现在几点？'], answer: '出口在哪儿？', feedback: "The hiker points. '那边!' (Over there!) Lily follows and finds the main trail. Sometimes getting lost leads to the best views." },
    { type: 'learn', title: 'At a Homestay', narrative: "Lily stays with a Bai minority family in Dali. They welcome her with tea and smiles.", speaker: 'lily', mood: 'grateful', dialogue: "Host: 欢迎！请坐！(Welcome! Please sit!)", words: [{ character: '在', pinyin: 'zài', english: 'At/in/on', context: 'I am in Dali. 我在大理。' }, { character: '家', pinyin: 'jiā', english: 'Home/family', context: 'Their home is warm. 他们的家很温暖。' }, { character: '前面', pinyin: 'qián miàn', english: 'In front', context: 'Erhai Lake is in front. 洱海在前面。' }] },
    { type: 'quiz', title: 'A Gift', narrative: "The Bai grandmother gives Lily a handmade bracelet.", dialogue: "Grandma: 送给你。(A gift for you.)", question: 'What should Lily say?', options: ['谢谢！很漂亮！', '多少钱？', '再见！', '在哪里？'], answer: '谢谢！很漂亮！', feedback: "Lily's eyes fill with tears. '谢谢,' she whispers. The grandmother pats her hand. No more words needed." },
    { type: 'end', title: 'Grandma\'s Secret', narrative: "Lily writes by Erhai Lake.", speaker: 'lily', mood: 'reflective', dialogue: "Grandma wrote about this lake. She said it was the most beautiful place in China. She was right. A Bai grandmother gave me a bracelet today. She reminded me of you, Grandma. I'm learning that kindness doesn't need perfect grammar." },
  ],
  Guangdong: [
    { type: 'intro', title: 'Family Ties', narrative: "Lily takes a train to Guangzhou. She's nervous — she's meeting her cousin Mei for the first time. Family she never knew she had.", speaker: 'narrator', mood: 'nervous', dialogue: "Lily: 'I have family here? Cousins I've never met? What do I even call them?'" },
    { type: 'learn', title: 'Family Words', narrative: "Mei meets Lily at the station. She's warm, funny, and speaks a mix of Mandarin and Cantonese.", speaker: 'mei', mood: 'warm', dialogue: "Mei: 你好！我是你的表妹！(Hello! I'm your cousin!)", words: [{ character: '爸爸', pinyin: 'bà ba', english: 'Father', context: 'Lily\'s father is Mei\'s uncle.' }, { character: '妈妈', pinyin: 'mā ma', english: 'Mother', context: 'Their grandmothers were sisters.' }, { character: '朋友', pinyin: 'péng yǒu', english: 'Friend', context: 'Mei quickly becomes Lily\'s friend.' }, { character: '认识', pinyin: 'rèn shi', english: 'To know (a person)', context: 'Nice to meet you! 认识你很高兴！' }] },
    { type: 'quiz', title: 'Dim Sum Morning', narrative: "Mei takes Lily for dim sum. The table fills with bamboo steamers.", dialogue: "Mei: 你会用筷子吗？(Can you use chopsticks?)", question: 'How does Lily say "I can use chopsticks"?', options: ['我会用筷子', '我喜欢筷子', '筷子很大', '我不会筷子'], answer: '我会用筷子', feedback: "Mei grins. 'Good! Because forks are NOT an option here!' She piles more dumplings onto Lily's plate." },
    { type: 'learn', title: 'Jobs & Life', narrative: "Over tea, Mei asks Lily about her life in America. Lily asks about Mei's work.", speaker: 'mei', mood: 'warm', dialogue: "Mei: 你做什么工作？(What do you do for work?)", words: [{ character: '工作', pinyin: 'gōng zuò', english: 'Work/job', context: 'What work do you do? 你做什么工作？' }, { character: '老师', pinyin: 'lǎo shī', english: 'Teacher', context: 'Mei is a teacher. 我是老师。' }, { character: '学生', pinyin: 'xué shēng', english: 'Student', context: 'Lily is a student of Chinese.' }, { character: '医生', pinyin: 'yī shēng', english: 'Doctor', context: 'Their aunt is a doctor.' }] },
    { type: 'quiz', title: 'The Tea Tap', narrative: "Mei pours tea for Lily. An older relative taps two fingers on the table.", dialogue: "Lily: 'Why did she tap the table?'", question: 'What does the finger tapping mean?', options: ['She is impatient', 'Thank you (for pouring tea)', 'The tea is too hot', 'She wants more tea'], answer: 'Thank you (for pouring tea)', feedback: "Mei explains the legend of the emperor in disguise. Lily tries it herself when pouring tea for Mei. The gesture feels natural — a silent thank you." },
    { type: 'end', title: 'New Family', narrative: "Lily writes in her journal after the family dinner.", speaker: 'lily', mood: 'grateful', dialogue: "I have family here. Real family. Mei taught me to tap two fingers to say thank you. We laughed at my Cantonese attempts. Grandma, you never told me about them. But I think you wanted me to find them myself." },
  ],
  Henan: [
    { type: 'intro', title: 'Shaolin Dreams', narrative: "Lily arrives at Shaolin Temple on Song Mountain. She's watched kung fu movies her whole life. The real thing is... humbling. Young monks practice in perfect synchronization, their movements impossibly precise.", speaker: 'narrator', mood: 'inspired', dialogue: "Lily: 'I tried to copy their stance. I lasted about 10 seconds before my legs gave out.'" },
    { type: 'learn', title: 'Abilities', narrative: "A young monk offers to teach Lily basic stances. She needs to talk about abilities.", speaker: 'monk', mood: 'patient', dialogue: "Monk: 你会做什么？(What can you do?)", words: [{ character: '会', pinyin: 'huì', english: 'Can (learned skill)', context: 'I can speak a little Chinese. 我会说一点中文。' }, { character: '能', pinyin: 'néng', english: 'Can (ability/possibility)', context: 'Can you teach me? 你能教我吗？' }, { character: '写', pinyin: 'xiě', english: 'To write', context: 'I can write some characters.' }, { character: '学', pinyin: 'xué', english: 'To learn', context: 'I am learning kung fu. 我在学功夫。' }] },
    { type: 'quiz', title: 'The Monk\'s Lesson', narrative: "After trying (and failing) at kung fu, Lily asks the monk a question.", dialogue: "Lily: 功夫很难吗？(Is kung fu hard?)", question: 'What does the monk probably answer?', options: ['很容易！(Very easy!)', '慢慢学。(Learn slowly.)', '很便宜。(Very cheap.)', '很大。(Very big.)'], answer: '慢慢学。(Learn slowly.)', feedback: "'Kung fu is not about speed,' the monk says. 'It's about patience. Same as learning Chinese. One word at a time.'" },
    { type: 'learn', title: 'Asking for Help', narrative: "Later, Lily gets lost in the temple complex. She needs to ask someone for directions.", speaker: 'lily', mood: 'lost', dialogue: "Lily: 'I need to ask for help. How do I say it?'", words: [{ character: '请问', pinyin: 'qǐng wèn', english: 'Excuse me / May I ask', context: 'Excuse me, where is the exit?' }, { character: '问', pinyin: 'wèn', english: 'To ask', context: 'I want to ask a question.' }, { character: '说', pinyin: 'shuō', english: 'To speak', context: 'Please speak slowly. 请慢慢说。' }] },
    { type: 'quiz', title: 'Finding the Way', narrative: "Lily approaches a senior monk sweeping the courtyard.", dialogue: "Monk: 你要去哪里？(Where do you want to go?)", question: 'What should Lily say?', options: ['请问，出口在哪儿？', '你好吗？', '功夫很难。', '我喜欢这里。'], answer: '请问，出口在哪儿？', feedback: "The monk smiles and points with his broom. '一直走。' (Go straight.) Lily bows — the Shaolin greeting, fist in palm. The monk bows back." },
    { type: 'end', title: 'Patience', narrative: "Lily writes on the bus leaving Shaolin.", speaker: 'lily', mood: 'reflective', dialogue: "I can't do kung fu. But I learned something better: patience. The monk said learning Chinese is like kung fu — you don't master it in a day. You show up, practice, fall down, get back up. One word at a time. 慢慢来." },
  ],
  Xinjiang: [
    { type: 'intro', title: 'The Silk Road', narrative: "Lily flies to Urumqi, then takes a bumpy bus to Kashgar. The landscape transforms — deserts, snow-capped mountains, oasis towns. This was the Silk Road. Traders, pilgrims, travelers — they all passed through here.", speaker: 'narrator', mood: 'adventurous', dialogue: "Lily: 'The Sunday bazaar has been running for 2,000 years. Marco Polo walked here. Now me.'" },
    { type: 'learn', title: 'Getting Around', narrative: "Lily needs to navigate the sprawling bazaar. Transportation words are essential.", speaker: 'lily', mood: 'focused', dialogue: "Lily: 'I need to get around. Taxi? Bus? Walk?'", words: [{ character: '去', pinyin: 'qù', english: 'To go', context: 'I go to the bazaar. 我去大巴扎。' }, { character: '出租车', pinyin: 'chū zū chē', english: 'Taxi', context: 'Take a taxi. 坐出租车。' }, { character: '飞机', pinyin: 'fēi jī', english: 'Airplane', context: 'I flew here. 我坐飞机来的。' }, { character: '在哪儿', pinyin: 'zài nǎr', english: 'Where is', context: 'Where is the bazaar? 大巴扎在哪儿？' }] },
    { type: 'quiz', title: 'Lost in Kashgar', narrative: "Lily gets lost in the maze-like old city. She needs help.", dialogue: "Lily: 'I don't know where I am. I need to ask someone.'", question: 'How does Lily ask for directions?', options: ['请问，怎么走？', '这个东西多少钱？', '你叫什么名字？', '现在几点？'], answer: '请问，怎么走？', feedback: "An elderly Uyghur woman takes Lily's hand and guides her through the alleys. She doesn't speak Mandarin, but kindness needs no translation." },
    { type: 'learn', title: 'Market Finds', narrative: "At the bazaar, Lily is overwhelmed by sights and smells: cumin, saffron, grilled lamb, fresh naan.", speaker: 'lily', mood: 'excited', dialogue: "Lily: 'I want to buy everything! But first — what is that amazing smell?'", words: [{ character: '买', pinyin: 'mǎi', english: 'To buy', context: 'I want to buy this. 我想买这个。' }, { character: '东西', pinyin: 'dōng xi', english: 'Things/stuff', context: 'So many things! 好多东西！' }, { character: '吃', pinyin: 'chī', english: 'To eat', context: 'I want to eat lamb skewers!' }] },
    { type: 'quiz', title: 'An Invitation', narrative: "The elderly woman who helped Lily invites her for tea. She gestures warmly.", dialogue: "Old woman: (gesturing) 来！喝茶！(Come! Drink tea!)", question: 'What should Lily say?', options: ['谢谢！(Thank you!)', '多少钱？(How much?)', '再见！(Goodbye!)', '对不起！(Sorry!)'], answer: '谢谢！(Thank you!)', feedback: "Lily sits with the woman, her daughter, her grandchildren. They share tea, naan, and smiles. Lily understands maybe 10% of the words — but 100% of the warmth." },
    { type: 'end', title: 'Silk Road Lessons', narrative: "Lily writes on the rooftop of her hostel, watching the sunset over Kashgar.", speaker: 'lily', mood: 'reflective', dialogue: "Today I got lost and found a family. An Uyghur grandmother held my hand. We shared tea without sharing a language. Maybe that's the real Silk Road — not silk or spices, but people meeting people. Grandma, did you feel this too?" },
  ],
  'Hong Kong': [
    { type: 'intro', title: 'The Final Stop', narrative: "Lily's last stop. Hong Kong's skyline rises from Victoria Harbour like a crystal garden. She thinks about her first day in Beijing — couldn't read a sign, couldn't ask for help. Now look at her.", speaker: 'narrator', mood: 'reflective', dialogue: "Lily: 'I started this journey with 你好 and 谢谢. Let's see how far I've come.'" },
    { type: 'learn', title: 'Review: Everyday Life', narrative: "Lily navigates Hong Kong with confidence. She reviews essential words from her journey.", speaker: 'lily', mood: 'confident', dialogue: "Lily: 'I can order food, ask for directions, introduce myself. Let's review!'", words: [{ character: '电话', pinyin: 'diàn huà', english: 'Telephone', context: 'Lily needs to make a call.' }, { character: '手机', pinyin: 'shǒu jī', english: 'Mobile phone', context: 'Her phone has photos from the whole trip.' }, { character: '书', pinyin: 'shū', english: 'Book', context: 'She bought a book about Hong Kong history.' }, { character: '牛奶', pinyin: 'niú nǎi', english: 'Milk', context: 'Hong Kong milk tea is famous!' }] },
    { type: 'quiz', title: 'The Peak', narrative: "Lily takes the Peak Tram to Victoria Peak. The view takes her breath away.", dialogue: "Lily: (to herself) 'I've come so far. From zero Chinese to... this.'", question: 'How might Lily describe the view?', options: ['很漂亮！(Beautiful!)', '太辣了！(Too spicy!)', '多少钱？(How much?)', '现在几点？(What time?)'], answer: '很漂亮！(Beautiful!)', feedback: "Hong Kong spreads out below her — mountains, harbor, skyscrapers, islands. '很漂亮,' she whispers. Her first Chinese word was 你好. Now she can describe beauty in another language." },
    { type: 'learn', title: 'Final Review', narrative: "Lily writes postcards to everyone she met on her journey.", speaker: 'lily', mood: 'grateful', dialogue: "Lily: 'I want to write thank you notes. In Chinese.'", words: [{ character: '谢谢', pinyin: 'xiè xie', english: 'Thank you', context: 'Thank you for everything. 谢谢你们。' }, { character: '再见', pinyin: 'zài jiàn', english: 'Goodbye', context: 'Not goodbye — see you again. 再见。' }, { character: '爱', pinyin: 'ài', english: 'Love', context: 'With love, Lily. 爱你的，小莉。' }] },
    { type: 'quiz', title: 'The Journal', narrative: "Lily opens her grandma's journal to the last page. There's a message she somehow missed.", dialogue: "Grandma's handwriting: '小莉，去中国吧。那里有你的根。'(Xiao Li, go to China. Your roots are there.)", question: 'Did Lily fulfill her grandma\'s wish?', options: ['Yes — she traveled across China and learned Chinese', 'No — she never left Beijing', 'She only visited one city', 'She gave up after day one'], answer: 'Yes — she traveled across China and learned Chinese', feedback: "Lily closes the journal. She DID learn Chinese. She DID find her roots. And somewhere along the way, she found herself too." },
    { type: 'end', title: 'See You Again', narrative: "Lily writes the final entry in her own travel journal, at Victoria Peak, as the sun sets over Hong Kong.", speaker: 'lily', mood: 'reflective', dialogue: "Grandma, I did it. 9 cities. 150+ words. Countless bowls of noodles, wrong turns, new friends, and moments of pure joy. I came to China to learn a language. I learned that language is just the beginning — it's the people, the food, the history, the kindness of strangers. 谢谢，奶奶。再见 — but not goodbye. I'll be back." },
  ],
};

async function main() {
  for (const [name, content] of Object.entries(stories)) {
    await prisma.province.updateMany({
      where: { name },
      data: { storyContent: JSON.stringify(content) },
    });
    console.log(`✅ ${name}: ${content.length} scenes`);
  }
  await prisma.$disconnect();
  console.log('\n🎉 All stories seeded!');
}
main().catch((e) => { console.error(e); process.exit(1); });
